// Generated by CoffeeScript 1.10.0



var DataOperationMap = {
    "http://softwareOntology.com/Constant": function(container, pageData) {
      return pageData.value;
    },
    "http://softwareOntology.com/local": function(cont, pageData) {
      var container
      toReturn = ""
      container = cont;
      while (container.parent !== void 0) {
        if (container.parent.localData[pageData.key] !== void 0) {
          toReturn = container.parent.localData[pageData.key]
          break;
        } else {
          container = container.parent;
        }
      }
      return toReturn;
    },
    "http://softwareOntology.com/global": function(cont, configData) {
    	return pageData[configData.name]
    },
    "http://softwareOntology.com/selectOperationResult" : function(cont, configData){
    	
    	var dataToSelect = DataOperationMap[configData.dataToSelect.type](cont, configData.dataToSelect)	
    	var selectCriteria = DataOperationMap[configData.selectCriteria.type](cont, configData.selectCriteria)	
    	var arr = []
    	$.each(dataToSelect, (function(index, object){
    		if(object[configData.selectField] == selectCriteria){
    			arr.push(object)
    		}
    	}).bind(this))
    	return arr
    },
    
  };


