// Generated by CoffeeScript 1.10.0

var getData1 = function(dataDescriptor){
	
	if(DataLib.getType(dataDescriptor) == "object"){
		return DataOperationMap[dataDescriptor.type](undefined, dataDescriptor)	
	} else {
		return dataDescriptor
	}
}

var getData = function(element, dataDescriptor){
	
	return DataOperationMap[dataDescriptor.type](element, dataDescriptor)
}

var DataOperationMap = {
		
    "http://softwareOntology.com/Constant": function(container, data) {
      return data.value;
    },
    
    "http://softwareOntology.com/local": function(container, pageData) {

    toReturn = ""
    while(container !== undefined) {
    	 if (container.localData !== undefined) {
          	if(container.localData[pageData.key] !== undefined){
          		toReturn = container.localData[pageData.key]
                  break;
          	} else {
          		container = container.parent
          	}
          } else {
            container = container.parent;
          }
      }
      if(toReturn == "" && pageData.defaultValue != undefined){
    	  toReturn = pageData.defaultValue
      }
      return toReturn; 
      
    },
    "http://softwareOntology.com/global": function(cont, configData) {
    	//if(pageData[configData.key] != undefined){
    	if(DataLib.getType(configData.key) == "object"){
    		return pageData[getData(cont, configData.key)]	
        } else if (pageData[getData1(configData.key)] != undefined){
    		return pageData[getData1(configData.key)]	
        } else {
    		return configData.defaultValue
        }
    },
        
    "http://softwareOntology.com/selectOperationResult" : function(cont, configData){
    	
    	var dataToSelect = DataOperationMap[configData.dataToSelect.type](cont, configData.dataToSelect)	
    	var selectCriteria = DataOperationMap[configData.selectCriteria.type](cont, configData.selectCriteria)	
    	var arr = []

    	$.each(dataToSelect, (function(index, object){
    		if(checkCriteria(object[configData.selectField], selectCriteria)){
    			arr.push(object)
    		}
    	}).bind(this))
    	return arr
    },
    
    "http://softwareOntology.com/fieldsOfArray" : function(cont, configData){
    	
    	arr = []
    	array = getData1(confiData.arrays)
    	$.each(array, function(index, object){
    		arr.push(object[configData.key])
    	})
    	return arr
    },
    
    "http://softwareOntology.com/Field" : function(cont, configData){
    	
    	of = getData1(configData.of)
    	type = DataLib.getType(of)
    	
    	toReturn = null
    	switch(DataLib.getType(of)){
    	
    	case "object" : 
    		toReturn = of[getData1(configData.key)]
    		break;
    	case "array" : 
    		arr = []
        	$.each(of, function(index, object){
        		arr = arr.concat(object[getData1(configData.key)])
        	})
        	toReturn =  arr
        	break;
    	default : break;
    	}
    	return toReturn
    }
}

var checkCriteria = function(value, selectCriteria){
	
	switch(DataLib.getType(selectCriteria)){
		
	case "array" : 
		return DataLib.or(value, selectCriteria)
		break;
	case "data" : 
		return value == selectCriteria
		break;
	}
}

