var swPrefix = "http://softwareOntology.com/"
var sw = {
		container : swPrefix + "Container",
		tabContainer :  swPrefix + "TabContainer",
		tab : swPrefix + "Tab",
		dataTable : swPrefix + "DataTable",
		dataField : swPrefix + "DataField",
		dataField : swPrefix + "DataField",
		literalField : swPrefix + "LiteralField",
		literalFieldMiddle : swPrefix + "LiteralFieldMiddle",
		editButton : swPrefix + "EditButton",
		linkDataTable : swPrefix + "LinkDataTable",
		selectorAddField : swPrefix + "SelectorAddField",
		global : swPrefix + "global",
		local : swPrefix + "local",
		constant : swPrefix + "Constant",
		selectOperationResult : swPrefix + "selectOperationResult",
		labelEditor : swPrefix + "labelEditor",
		imagesField : swPrefix + "ImagesField",
		existence : swPrefix + "Existence",
		onPageEditor : swPrefix + "OnPageEditor",
		literalEditor : swPrefix + "LiteralEditor",
		textEditor : swPrefix + "TextEditor",
		selectEditor : swPrefix + "SelectEditor",
		linkField : swPrefix + "LinkField",
}